import type { Grape } from '@/schema'

/**
 * Starter grape list. Every entry is `verified: false` until reviewed by the developer.
 * Profile ranges describe typical classic expressions of the grape, not every possible wine.
 */
export const grapes: Grape[] = [
  // ---------------------------------------------------------------- Red
  {
    id: 'cabernet-sauvignon',
    name: 'Cabernet Sauvignon',
    aliases: [],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [4, 5],
      alcohol: [3, 5],
      body: [4, 5],
      finish: [4, 5],
    },
    keyDescriptors: ['blackcurrant', 'cedar', 'green-bell-pepper', 'tobacco', 'mint'],
    verified: false,
    sources: [],
  },
  {
    id: 'merlot',
    name: 'Merlot',
    aliases: [],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [3, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['red-plum', 'black-plum', 'black-cherry', 'chocolate', 'cedar'],
    verified: false,
    sources: [],
  },
  {
    id: 'pinot-noir',
    name: 'Pinot Noir',
    aliases: ['Spätburgunder', 'Pinot Nero'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [2, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [2, 3],
      alcohol: [3, 4],
      body: [2, 3],
      finish: [3, 4],
    },
    keyDescriptors: ['red-cherry', 'raspberry', 'strawberry', 'forest-floor', 'mushroom'],
    verified: false,
    sources: [],
  },
  {
    id: 'syrah',
    name: 'Syrah',
    aliases: ['Shiraz'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [3, 4],
      alcohol: [3, 5],
      body: [4, 5],
      finish: [4, 5],
    },
    keyDescriptors: ['blackberry', 'black-pepper', 'violet', 'smoke', 'liquorice'],
    verified: false,
    sources: [],
  },
  {
    id: 'grenache',
    name: 'Grenache',
    aliases: ['Garnacha', 'Cannonau'],
    color: 'red',
    origin: 'spain',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [2, 3],
      tannin: [2, 4],
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['strawberry', 'raspberry', 'dried-herbs', 'white-pepper', 'liquorice'],
    notes: 'Origin is generally given as Aragón in Spain, though Sardinia also claims it.',
    verified: false,
    sources: [],
  },
  {
    id: 'tempranillo',
    name: 'Tempranillo',
    aliases: ['Tinta Roriz', 'Tinto Fino', 'Aragonez'],
    color: 'red',
    origin: 'spain',
    typicalProfile: {
      intensity: [3, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [3, 5],
      alcohol: [3, 5],
      body: [3, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['red-cherry', 'red-plum', 'vanilla', 'coconut', 'leather'],
    verified: false,
    sources: [],
  },
  {
    id: 'sangiovese',
    name: 'Sangiovese',
    aliases: ['Brunello', 'Prugnolo Gentile'],
    color: 'red',
    origin: 'italy',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: [4, 5],
      alcohol: [3, 4],
      body: [3, 4],
      finish: [3, 5],
    },
    keyDescriptors: ['red-cherry', 'red-plum', 'dried-herbs', 'tomato-leaf', 'leather'],
    verified: false,
    sources: [],
  },
  {
    id: 'nebbiolo',
    name: 'Nebbiolo',
    aliases: ['Spanna', 'Chiavennasca'],
    color: 'red',
    origin: 'italy',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: [5, 5],
      alcohol: [4, 4],
      body: [3, 4],
      finish: [4, 5],
    },
    keyDescriptors: ['rose', 'tar', 'red-cherry', 'liquorice', 'dried-herbs'],
    verified: false,
    sources: [],
  },
  {
    id: 'malbec',
    name: 'Malbec',
    aliases: ['Côt', 'Auxerrois'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['blackberry', 'black-plum', 'violet', 'chocolate', 'vanilla'],
    verified: false,
    sources: [],
  },
  {
    id: 'zinfandel',
    name: 'Zinfandel',
    aliases: ['Primitivo', 'Tribidrag', 'Crljenak Kaštelanski'],
    color: 'red',
    origin: 'croatia',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 2],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [5, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['blackberry', 'raspberry', 'dried-fruit', 'black-pepper', 'liquorice'],
    notes: 'DNA studies identify Zinfandel/Primitivo with the Croatian grape Tribidrag.',
    verified: false,
    sources: [],
  },
  {
    id: 'gamay',
    name: 'Gamay',
    aliases: ['Gamay Noir'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [2, 2],
      alcohol: [2, 3],
      body: [2, 2],
      finish: [2, 3],
    },
    keyDescriptors: ['raspberry', 'red-cherry', 'cranberry', 'banana', 'violet'],
    verified: false,
    sources: [],
  },
  {
    id: 'cabernet-franc',
    name: 'Cabernet Franc',
    aliases: ['Breton', 'Bouchet'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [3, 3],
      alcohol: [2, 4],
      body: [2, 3],
      finish: [3, 3],
    },
    keyDescriptors: ['raspberry', 'redcurrant', 'green-bell-pepper', 'violet', 'tobacco'],
    verified: false,
    sources: [],
  },
  {
    id: 'barbera',
    name: 'Barbera',
    aliases: [],
    color: 'red',
    origin: 'italy',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: [2, 3],
      alcohol: [3, 4],
      body: [3, 3],
      finish: [3, 3],
    },
    keyDescriptors: ['red-cherry', 'red-plum', 'blackberry', 'black-pepper'],
    verified: false,
    sources: [],
  },

  // ---------------------------------------------------------------- White
  {
    id: 'chardonnay',
    name: 'Chardonnay',
    aliases: [],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [2, 4],
      sweetness: [1, 1],
      acidity: [3, 5],
      tannin: null,
      alcohol: [3, 5],
      body: [2, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['green-apple', 'lemon', 'peach', 'pineapple', 'butter', 'toast'],
    notes: 'Very site- and winemaking-dependent; ranges are deliberately wide.',
    verified: false,
    sources: [],
  },
  {
    id: 'sauvignon-blanc',
    name: 'Sauvignon Blanc',
    aliases: ['Fumé Blanc'],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    keyDescriptors: ['gooseberry', 'grapefruit', 'grass', 'passion-fruit', 'elderflower'],
    verified: false,
    sources: [],
  },
  {
    id: 'riesling',
    name: 'Riesling',
    aliases: [],
    color: 'white',
    origin: 'germany',
    typicalProfile: {
      intensity: [3, 5],
      sweetness: [1, 4],
      acidity: [5, 5],
      tannin: null,
      alcohol: [1, 3],
      body: [1, 3],
      finish: [3, 5],
    },
    keyDescriptors: ['lime', 'green-apple', 'peach', 'wet-stone', 'honeysuckle', 'petrol'],
    verified: false,
    sources: [],
  },
  {
    id: 'chenin-blanc',
    name: 'Chenin Blanc',
    aliases: ['Steen', 'Pineau de la Loire'],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 4],
      acidity: [5, 5],
      tannin: null,
      alcohol: [2, 4],
      body: [2, 3],
      finish: [3, 4],
    },
    keyDescriptors: ['green-apple', 'quince', 'honey', 'wax', 'chalk'],
    verified: false,
    sources: [],
  },
  {
    id: 'pinot-grigio',
    name: 'Pinot Grigio',
    aliases: ['Pinot Gris', 'Grauburgunder', 'Ruländer'],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [2, 4],
      sweetness: [1, 3],
      acidity: [2, 4],
      tannin: null,
      alcohol: [2, 4],
      body: [2, 4],
      finish: [2, 4],
    },
    keyDescriptors: ['pear', 'lemon', 'peach', 'honey', 'ginger'],
    notes:
      'A colour mutation of Pinot Noir from Burgundy. Light Italian and rich Alsatian styles differ a lot.',
    verified: false,
    sources: [],
  },
  {
    id: 'gewurztraminer',
    name: 'Gewürztraminer',
    aliases: ['Traminer', 'Traminer Aromatico'],
    color: 'white',
    origin: 'italy',
    typicalProfile: {
      intensity: [5, 5],
      sweetness: [1, 3],
      acidity: [2, 2],
      tannin: null,
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['lychee', 'rose', 'ginger', 'honey', 'orange-peel'],
    notes: 'Named after Tramin in Alto Adige; classic home today is Alsace.',
    verified: false,
    sources: [],
  },
  {
    id: 'viognier',
    name: 'Viognier',
    aliases: [],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [2, 3],
      tannin: null,
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['apricot', 'peach', 'honeysuckle', 'orange-blossom'],
    verified: false,
    sources: [],
  },
  {
    id: 'albarino',
    name: 'Albariño',
    aliases: ['Alvarinho'],
    color: 'white',
    origin: 'spain',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 3],
      finish: [3, 3],
    },
    keyDescriptors: ['grapefruit', 'lemon', 'peach', 'saline'],
    verified: false,
    sources: [],
  },
  {
    id: 'gruner-veltliner',
    name: 'Grüner Veltliner',
    aliases: [],
    color: 'white',
    origin: 'austria',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 4],
      finish: [3, 4],
    },
    keyDescriptors: ['green-apple', 'grapefruit', 'white-pepper', 'wet-stone'],
    verified: false,
    sources: [],
  },
  {
    id: 'semillon',
    name: 'Sémillon',
    aliases: [],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [2, 4],
      sweetness: [1, 5],
      acidity: [3, 4],
      tannin: null,
      alcohol: [2, 4],
      body: [3, 5],
      finish: [3, 5],
    },
    keyDescriptors: ['lemon', 'apricot', 'honey', 'wax', 'toast'],
    notes: 'Dry Bordeaux blends and botrytised Sauternes give very different profiles.',
    verified: false,
    sources: [],
  },
  {
    id: 'muscat',
    name: 'Muscat',
    aliases: ['Muscat Blanc à Petits Grains', 'Moscato', 'Moscatel'],
    color: 'white',
    origin: 'greece',
    typicalProfile: {
      intensity: [5, 5],
      sweetness: [1, 5],
      acidity: [2, 3],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 3],
      finish: [2, 3],
    },
    keyDescriptors: ['grape', 'orange-blossom', 'rose', 'honey'],
    notes: 'Origin is uncertain; Greece/eastern Mediterranean is commonly cited. Needs review.',
    verified: false,
    sources: [],
  },
  {
    id: 'garganega',
    name: 'Garganega',
    aliases: [],
    color: 'white',
    origin: 'italy',
    typicalProfile: {
      intensity: [2, 3],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [2, 3],
    },
    keyDescriptors: ['pear', 'lemon', 'melon', 'nuts', 'chalk'],
    verified: false,
    sources: [],
  },
]
