import type { Grape } from '@/schema'

/**
 * Starter grape list. Every entry is `verified: false` until reviewed by the developer.
 * Profile ranges describe typical classic expressions of the grape, not every possible wine.
 */
export const grapes: Grape[] = [
  // ---------------------------------------------------------------- Red
  {
    id: 'cabernet-sauvignon',
    name: 'Cabernet Sauvignon',
    aliases: [],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [4, 5],
      alcohol: [3, 5],
      body: [4, 5],
      finish: [4, 5],
    },
    keyDescriptors: ['blackcurrant', 'cedar', 'green-bell-pepper', 'tobacco', 'mint'],
    story: [
      "Cabernet Sauvignon er en forholdsvis ung drue. DNA-analyser fra 1990'erne viste, at den er en naturlig krydsning mellem Cabernet Franc og Sauvignon Blanc, og den er formentlig opstået i Bordeaux i 1600-tallet.",
      'Den tykke skind og sene modning gør den robust i marken og giver vine med masser af tannin og farve. I Médoc er den rygraden i de klassiske blandinger med Merlot og Cabernet Franc.',
      'Fra Bordeaux har druen bredt sig til stort set alle vinlande: Napa Valley, Coonawarra, Chile og Toscana (i de såkaldte supertoscanere). Den er i dag en af verdens mest plantede druer.',
    ],
    verified: true,
    sources: [
      'Wine Folly, cabernet-sauvignon grape profile, https://winefolly.com/grapes/cabernet-sauvignon/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'merlot',
    name: 'Merlot',
    aliases: [],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [3, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['red-plum', 'black-plum', 'black-cherry', 'chocolate', 'cedar'],
    story: [
      "Merlot stammer fra Bordeaux, hvor den er den mest plantede drue. Navnet forbindes traditionelt med 'merle', fransk for solsort, som angiveligt holder af de mørke, tidligt modne bær.",
      'Cabernet Franc er den ene forælder til Merlot, og de to druer deler derfor mange træk. Merlot modner tidligere end Cabernet Sauvignon og giver blødere, rundere vine med mere frugt.',
      "På Bordeaux' højre bred, i Pomerol og Saint-Émilion, spiller Merlot hovedrollen, mens den på venstre bred blødgør Cabernet Sauvignon i blandingerne.",
    ],
    verified: false,
    sources: [],
  },
  {
    id: 'pinot-noir',
    name: 'Pinot Noir',
    aliases: ['Spätburgunder', 'Pinot Nero'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [2, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [2, 3],
      alcohol: [3, 4],
      body: [2, 3],
      finish: [3, 4],
    },
    keyDescriptors: ['red-cherry', 'raspberry', 'strawberry', 'forest-floor', 'mushroom'],
    story: [
      'Pinot Noir er en af de ældste kendte vindruer og har været dyrket i Bourgogne siden middelalderen. Den er også forælder til Chardonnay, Gamay og Aligoté, alle krydsninger med den gamle drue Gouais Blanc.',
      'Druen muterer let. Pinot Gris, Pinot Blanc og Pinot Meunier er alle farvevarianter af samme drue. Den tynde skind gør den følsom over for råd og vejr, og den er kendt som en drue, der kræver præcision af både vinbonde og vinmager.',
      'Bourgogne er stadig referencen, men Pinot Noir er også grunddrue i Champagne og har fundet nye hjem i Oregon, Central Otago, Tyskland (som Spätburgunder) og på Sydafrikas og Californiens kølige kyster.',
    ],
    verified: true,
    sources: [
      'Wine Folly, pinot-noir grape profile, https://winefolly.com/grapes/pinot-noir/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'syrah',
    name: 'Syrah',
    aliases: ['Shiraz'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [3, 4],
      alcohol: [3, 5],
      body: [4, 5],
      finish: [4, 5],
    },
    keyDescriptors: ['blackberry', 'black-pepper', 'violet', 'smoke', 'liquorice'],
    story: [
      'Syrah hører hjemme i det nordlige Rhône, hvor Hermitage og Côte-Rôtie har givet den ry i århundreder. En sejlivet myte knytter druen til byen Shiraz i Persien, men DNA-analyser fra 1998 viste, at den er en krydsning mellem to lokale franske druer, Dureza og Mondeuse Blanche.',
      "Til Australien kom druen i 1830'erne, hvor den fik navnet Shiraz og med tiden blev landets vigtigste drue. Barossa Valley har nogle af verdens ældste Syrah-vinstokke, plantet i 1800-tallet.",
      'Stilen spænder fra det nordlige Rhônes peberede, stramme vine til de fyldige, mørke Shiraz fra varme australske egne.',
    ],
    verified: true,
    sources: [
      'Wine Folly, syrah grape profile, https://winefolly.com/grapes/syrah/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'grenache',
    name: 'Grenache',
    aliases: ['Garnacha', 'Cannonau'],
    color: 'red',
    origin: 'spain',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [2, 3],
      tannin: [2, 4],
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['strawberry', 'raspberry', 'dried-herbs', 'white-pepper', 'liquorice'],
    story: [
      'Grenache, på spansk Garnacha, stammer efter de fleste kilder fra Aragón i det nordøstlige Spanien, selvom Sardinien også gør krav på den under navnet Cannonau.',
      'Druen tåler varme og tørke og dyrkes ofte som fritstående buske. Den giver vine med højt alkoholindhold og blød tannin, og den er hovedbestanddelen i Châteauneuf-du-Pape og de fleste blandinger fra det sydlige Rhône.',
      'I Spanien er den central i Priorat og indgår i Rioja-blandinger, og i Provence og Tavel er den grundlaget for rosé. Australien har bevaret gamle Grenache-stokke i Barossa og McLaren Vale.',
    ],
    note: 'Origin is generally given as Aragón in Spain, though Sardinia also claims it.',
    verified: true,
    sources: [
      'Wine Folly, grenache grape profile, https://winefolly.com/grapes/grenache/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'tempranillo',
    name: 'Tempranillo',
    aliases: ['Tinta Roriz', 'Tinto Fino', 'Aragonez'],
    color: 'red',
    origin: 'spain',
    typicalProfile: {
      intensity: [3, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [3, 5],
      alcohol: [3, 5],
      body: [3, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['red-cherry', 'red-plum', 'vanilla', 'coconut', 'leather'],
    story: [
      "Tempranillo er Spaniens vigtigste røde drue. Navnet kommer af 'temprano', spansk for tidlig, fordi den modner flere uger før andre spanske druer.",
      'Druen har mange lokale navne: Tinto Fino og Tinta del País i Ribera del Duero, Tinta de Toro i Toro, og Tinta Roriz eller Aragonez i Portugal, hvor den indgår i portvin.',
      'I Rioja er Tempranillo grundlaget for den klassiske fadlagringstradition, hvor betegnelserne crianza, reserva og gran reserva angiver, hvor længe vinen har ligget på fad og flaske, før den sælges.',
    ],
    verified: true,
    sources: [
      'Wine Folly, tempranillo grape profile, https://winefolly.com/grapes/tempranillo/ (hentet 2026-09-17)',
      'Wikipedia, Rioja (wine), https://en.wikipedia.org/wiki/Rioja_(wine) (hentet 2026-09-17)',
    ],
  },
  {
    id: 'sangiovese',
    name: 'Sangiovese',
    aliases: ['Brunello', 'Prugnolo Gentile'],
    color: 'red',
    origin: 'italy',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: [4, 5],
      alcohol: [3, 4],
      body: [3, 4],
      finish: [3, 5],
    },
    keyDescriptors: ['red-cherry', 'red-plum', 'dried-herbs', 'tomato-leaf', 'leather'],
    story: [
      "Sangiovese er Italiens mest plantede drue og hjertet i Toscana. Navnet fortolkes traditionelt som 'sanguis Jovis', Jupiters blod, men den forklaring er nok mere poesi end historie.",
      'DNA-studier har vist, at druen er en krydsning mellem Ciliegiolo og den obskure syditalienske drue Calabrese di Montenuovo.',
      "Den kendes under lokale navne rundt om i Toscana: Brunello i Montalcino og Prugnolo Gentile i Montepulciano. Chianti, Brunello di Montalcino og Vino Nobile di Montepulciano bygger alle på Sangiovese, og siden 1970'erne har druen også indgået i de såkaldte supertoscanere.",
    ],
    verified: true,
    sources: [
      'Wine Folly, sangiovese grape profile, https://winefolly.com/grapes/sangiovese/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'nebbiolo',
    name: 'Nebbiolo',
    aliases: ['Spanna', 'Chiavennasca'],
    color: 'red',
    origin: 'italy',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: [5, 5],
      alcohol: [4, 4],
      body: [4, 5],
      finish: [4, 5],
    },
    keyDescriptors: ['rose', 'tar', 'red-cherry', 'liquorice', 'dried-herbs'],
    story: [
      "Nebbiolo er Piemontes store drue og nævnes i skriftlige kilder helt tilbage til 1200-tallet. Navnet forbindes normalt med 'nebbia', italiensk for tåge, fordi druen høstes sent i oktober, når tågen ligger over Langhe-bakkerne.",
      'Druen er krævende: den blomstrer tidligt, modner sent og er meget følsom over for jord og placering. Til gengæld giver den vine med lys farve, men høj syre og kraftig tannin, og en aroma af tjære og roser.',
      'Barolo og Barbaresco er de berømte udtryk, men Nebbiolo dyrkes også i Valtellina i Lombardiet (som Chiavennasca) og i Gattinara og Ghemme i det nordlige Piemonte (som Spanna).',
    ],
    verified: true,
    sources: [
      'Wine Folly, nebbiolo grape profile, https://winefolly.com/grapes/nebbiolo/ (hentet 2026-09-17)',
      'Wikipedia, Barolo, https://en.wikipedia.org/wiki/Barolo (hentet 2026-09-17)',
    ],
  },
  {
    id: 'malbec',
    name: 'Malbec',
    aliases: ['Côt', 'Auxerrois'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [2, 3],
      tannin: [3, 4],
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['blackberry', 'black-plum', 'violet', 'chocolate', 'vanilla'],
    story: [
      "Malbec stammer fra det sydvestlige Frankrig, hvor den i Cahors kaldes Côt og har givet den mørke 'sorte vin', der var berømt allerede i middelalderen. I Bordeaux er den i dag en lille bidrue.",
      'Ifølge den gængse fortælling kom druen til Argentina i 1853 med den franske agronom Michel Aimé Pouget, som Domingo Sarmiento hentede til Mendoza for at grundlægge en landbrugsskole. I Mendozas højtliggende, solrige vinmarker fandt Malbec et nyt hjem og blev landets nationaldrue.',
      'Den hårde frost i 1956 udryddede mange Malbec-stokke i Bordeaux, og druen blev sjældent genplantet dér. Argentina har i dag langt flere Malbec-vinmarker end Frankrig.',
    ],
    verified: true,
    sources: [
      'Wine Folly, malbec grape profile, https://winefolly.com/grapes/malbec/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'zinfandel',
    name: 'Zinfandel',
    aliases: ['Primitivo', 'Tribidrag', 'Crljenak Kaštelanski'],
    color: 'red',
    origin: 'croatia',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 2],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [5, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['blackberry', 'raspberry', 'dried-fruit', 'black-pepper', 'liquorice'],
    story: [
      'Zinfandels oprindelse var længe et mysterium. Efter årtiers detektivarbejde viste DNA-analyser i 2001, at den er identisk med den kroatiske drue Tribidrag (Crljenak Kaštelanski) og med Primitivo fra Puglia i Syditalien.',
      "Druen kom til USA's østkyst i 1820'erne, formentlig via den kejserlige planteskole i Wien, og fulgte med guldgraverne til Californien, hvor den blev en af statens vigtigste druer.",
      "I 1970'erne blev den halvsøde, lyserøde 'White Zinfandel' en kæmpesucces og reddede paradoksalt nok mange gamle vinstokke fra at blive rykket op. I dag laves der kraftige, modne rødvine på gamle Zinfandel-stokke i Sonoma, Napa og Lodi.",
    ],
    note: 'DNA studies identify Zinfandel/Primitivo with the Croatian grape Tribidrag.',
    verified: false,
    sources: [],
  },
  {
    id: 'gamay',
    name: 'Gamay',
    aliases: ['Gamay Noir'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [2, 2],
      alcohol: [2, 3],
      body: [2, 2],
      finish: [2, 3],
    },
    keyDescriptors: ['raspberry', 'red-cherry', 'cranberry', 'banana', 'violet'],
    story: [
      "Gamay er, ligesom Chardonnay, et barn af Pinot Noir og Gouais Blanc og opstod i Bourgogne. I 1395 forbød hertug Filip den Dristige druen i Bourgogne som 'illoyal' og skadelig, fordi den udkonkurrerede Pinot Noir.",
      'Druen fandt i stedet hjem længere sydpå i Beaujolais, hvor granitjorden passer den. Her laves de fleste vine med kulsyremaceration, som fremhæver frisk, rød frugt og giver bløde tanniner.',
      'Beaujolais Nouveau gjorde druen berømt for lette, hurtigt drukne vine, men de ti Beaujolais-cruer som Morgon, Fleurie og Moulin-à-Vent viser, at Gamay også kan give seriøse vine med lagringspotentiale.',
    ],
    verified: true,
    sources: [
      'Wine Folly, gamay grape profile, https://winefolly.com/grapes/gamay/ (hentet 2026-09-17)',
      'Wikipedia, Beaujolais, https://en.wikipedia.org/wiki/Beaujolais (hentet 2026-09-17)',
    ],
  },
  {
    id: 'cabernet-franc',
    name: 'Cabernet Franc',
    aliases: ['Breton', 'Bouchet'],
    color: 'red',
    origin: 'france',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [3, 3],
      alcohol: [2, 4],
      body: [2, 3],
      finish: [3, 3],
    },
    keyDescriptors: ['raspberry', 'redcurrant', 'green-bell-pepper', 'violet', 'tobacco'],
    story: [
      'Cabernet Franc er den ældre af Cabernet-druerne og forælder til både Cabernet Sauvignon, Merlot og Carménère. Oprindelsen er usikker, men det sydvestlige Frankrig og det spanske Baskerland nævnes ofte.',
      'Druen modner tidligere end Cabernet Sauvignon og klarer sig derfor bedre i kølige egne. I Loire giver den de urtede, saftige rødvine fra Chinon, Bourgueil og Saumur-Champigny.',
      'I Bordeaux bruges den mest som bidrue, men i Saint-Émilion spiller den en større rolle, ikke mindst på Château Cheval Blanc, hvor den udgør en stor del af blandingen.',
    ],
    verified: false,
    sources: [],
  },
  {
    id: 'barbera',
    name: 'Barbera',
    aliases: [],
    color: 'red',
    origin: 'italy',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: [2, 3],
      alcohol: [3, 4],
      body: [3, 3],
      finish: [3, 3],
    },
    keyDescriptors: ['red-cherry', 'red-plum', 'blackberry', 'black-pepper'],
    story: [
      'Barbera er Piemontes mest plantede drue og har traditionelt været bøndernes hverdagsvin, mens Nebbiolo fik æren. Den giver mørk farve, høj syre og lav tannin, en usædvanlig kombination.',
      "I 1980'erne viste producenter som Giacomo Bologna med vinen Bricco dell'Uccellone, at Barbera lagret på små, nye egefade kunne blive en seriøs vin, og det ændrede druens omdømme.",
      "Barbera d'Asti og Barbera d'Alba er de klassiske betegnelser. Druen er også udvandret med italienske emigranter til Californien og Argentina.",
    ],
    verified: false,
    sources: [],
  },

  // ---------------------------------------------------------------- White
  {
    id: 'chardonnay',
    name: 'Chardonnay',
    aliases: [],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [2, 4],
      sweetness: [1, 1],
      acidity: [3, 5],
      tannin: null,
      alcohol: [3, 5],
      body: [2, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['green-apple', 'lemon', 'peach', 'pineapple', 'butter', 'toast'],
    story: [
      'Chardonnay stammer fra Bourgogne og har navn efter en lille landsby i Mâconnais. Den er en krydsning mellem Pinot Noir og Gouais Blanc, en gammel drue som viste sig at være forælder til en lang række franske druer.',
      'Druen er usædvanlig tilpasningsdygtig og forholdsvis neutral i sig selv, så stilen afhænger meget af klima og vinmager: stål og mineralitet i Chablis, fylde og nødder i Meursault, og frugt og smør i varme egne med ny eg.',
      "Chardonnay er hoveddruen i Champagne (blanc de blancs laves udelukkende på Chardonnay) og er blevet plantet i stort set alle vinlande. Reaktionen på de mest egetunge udgaver i 1990'erne, kendt som 'ABC' (Anything But Chardonnay), førte til mere afdæmpede stilarter.",
    ],
    note: 'Very site- and winemaking-dependent; ranges are deliberately wide.',
    verified: true,
    sources: [
      'Wine Folly, chardonnay grape profile, https://winefolly.com/grapes/chardonnay/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'sauvignon-blanc',
    name: 'Sauvignon Blanc',
    aliases: ['Fumé Blanc'],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    keyDescriptors: ['gooseberry', 'grapefruit', 'grass', 'passion-fruit', 'elderflower'],
    story: [
      "Sauvignon Blanc hører hjemme i Frankrig, i Loire og Bordeaux. Navnet menes at komme af 'sauvage', vild, og druen er forælder til Cabernet Sauvignon.",
      'I Loire giver Sancerre og Pouilly-Fumé den klassiske stramme, mineralske stil. I Bordeaux blandes den med Sémillon til både tørre hvidvine og de søde vine fra Sauternes.',
      "Marlborough i New Zealand gjorde druen til en verdensstjerne. De første stokke blev plantet i 1970'erne, og de eksplosivt aromatiske vine med stikkelsbær og passionsfrugt blev fra midten af 1980'erne et af vinverdenens mest genkendelige udtryk.",
    ],
    verified: true,
    sources: [
      'Wine Folly, sauvignon-blanc grape profile, https://winefolly.com/grapes/sauvignon-blanc/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'riesling',
    name: 'Riesling',
    aliases: [],
    color: 'white',
    origin: 'germany',
    typicalProfile: {
      intensity: [3, 5],
      sweetness: [1, 4],
      acidity: [5, 5],
      tannin: null,
      alcohol: [1, 3],
      body: [1, 3],
      finish: [3, 5],
    },
    keyDescriptors: ['lime', 'green-apple', 'peach', 'wet-stone', 'honeysuckle', 'petrol'],
    story: [
      'Riesling er Tysklands store drue og nævnes første gang i en kilde fra Rüsselsheim ved Rhinen i 1435. Gouais Blanc er den ene forælder.',
      'Druen modner sent og tåler kulde, hvilket passer til de stejle skiferskråninger langs Mosel og Rhinen. Den bevarer høj syre selv ved fuld modenhed og kan derfor laves i alle sødmegrader, fra knastør til Trockenbeerenauslese.',
      'Riesling er en af de hvide druer, der lagrer bedst. Med alderen udvikler den en karakteristisk note af petroleum. Uden for Tyskland er Alsace, Wachau i Østrig, Clare og Eden Valley i Australien og Finger Lakes i USA vigtige Riesling-områder.',
    ],
    verified: true,
    sources: [
      'Wine Folly, riesling grape profile, https://winefolly.com/grapes/riesling/ (hentet 2026-09-17)',
      'Wikipedia, German wine classification, https://en.wikipedia.org/wiki/German_wine_classification (hentet 2026-09-17)',
    ],
  },
  {
    id: 'chenin-blanc',
    name: 'Chenin Blanc',
    aliases: ['Steen', 'Pineau de la Loire'],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 4],
      acidity: [5, 5],
      tannin: null,
      alcohol: [2, 4],
      body: [2, 3],
      finish: [3, 4],
    },
    keyDescriptors: ['green-apple', 'quince', 'honey', 'wax', 'chalk'],
    story: [
      'Chenin Blanc er Loires alsidige drue og har været dyrket i Anjou siden middelalderen. Fra Vouvray, Savennières og Anjou laves alt fra tørre, mineralske vine over mousserende til søde, botrytiserede vine.',
      'Sydafrika har verdens største Chenin-arealer. Druen kom til Kap med de første hollandske bosættere i 1600-tallet og var i mange år kendt som Steen. De seneste årtier har sydafrikanske producenter lavet nogle af verdens bedste tørre Chenin på gamle buskvinstokke.',
      'Druen har naturligt høj syre, hvilket gør både de søde og de tørre vine meget holdbare.',
    ],
    verified: false,
    sources: [],
  },
  {
    id: 'pinot-grigio',
    name: 'Pinot Grigio',
    aliases: ['Pinot Gris', 'Grauburgunder', 'Ruländer'],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [2, 4],
      sweetness: [1, 3],
      acidity: [2, 4],
      tannin: null,
      alcohol: [2, 4],
      body: [2, 4],
      finish: [2, 4],
    },
    keyDescriptors: ['pear', 'lemon', 'peach', 'honey', 'ginger'],
    story: [
      'Pinot Grigio, eller Pinot Gris, er en farvemutation af Pinot Noir og stammer ligesom den fra Bourgogne. Bærrene er gråligt rosa, hvilket gav druen navn.',
      "I Alsace laves den i en fyldig, krydret stil (tidligere under navnet Tokay d'Alsace), og i Tyskland kaldes den Grauburgunder. Det er dog Italiens nordøstlige egne, Veneto, Friuli og Alto Adige, der gjorde den lette og friske Pinot Grigio til en af verdens mest solgte hvidvine.",
      'Oregon i USA har taget den franske stavemåde til sig og laver Pinot Gris i en stil, der ligger mellem den franske og den italienske.',
    ],
    note: 'A colour mutation of Pinot Noir from Burgundy. Light Italian and rich Alsatian styles differ a lot.',
    verified: true,
    sources: [
      'Wine Folly, pinot-grigio grape profile, https://winefolly.com/grapes/pinot-grigio/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'gewurztraminer',
    name: 'Gewürztraminer',
    aliases: ['Traminer', 'Traminer Aromatico'],
    color: 'white',
    origin: 'italy',
    typicalProfile: {
      intensity: [5, 5],
      sweetness: [1, 3],
      acidity: [1, 2],
      tannin: null,
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['lychee', 'rose', 'ginger', 'honey', 'orange-peel'],
    story: [
      "Gewürztraminer er en særligt aromatisk mutation af Traminer, en gammel drue, der har navn efter byen Tramin i Alto Adige i Norditalien. 'Gewürz' betyder krydret på tysk.",
      'Druens klassiske hjem i dag er Alsace, hvor den giver dybt gyldne, kraftige vine med lav syre og en umiskendelig aroma af litchi, rose og krydderier.',
      'Fordi druen mister syre hurtigt under modningen, dyrkes den bedst i kølige egne. Alto Adige, Pfalz, New Zealand og Alsace er blandt de vigtigste områder.',
    ],
    note: 'Named after Tramin in Alto Adige; classic home today is Alsace.',
    verified: true,
    sources: [
      'Wine Folly, gewurztraminer grape profile, https://winefolly.com/grapes/gewurztraminer/ (hentet 2026-09-17)',
    ],
  },
  {
    id: 'viognier',
    name: 'Viognier',
    aliases: [],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [2, 3],
      tannin: null,
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    keyDescriptors: ['apricot', 'peach', 'honeysuckle', 'orange-blossom'],
    story: [
      "Viognier hører hjemme i det nordlige Rhône, hvor Condrieu og den lille appellation Château-Grillet er dens klassiske udtryk. I 1960'erne var druen tæt på at forsvinde, og der var kun få hektar tilbage i Condrieu.",
      "Siden 1980'erne har den fået en renæssance. I Côte-Rôtie fermenteres den traditionelt sammen med Syrah, hvor den giver duft og stabiliserer farven, selvom den kun udgør en lille del.",
      'Druen er i dag plantet i Languedoc, Californien og Australien, hvor Yalumba var tidligt ude. Den giver fyldige vine med aroma af abrikos og fersken og forholdsvis lav syre.',
    ],
    verified: false,
    sources: [],
  },
  {
    id: 'albarino',
    name: 'Albariño',
    aliases: ['Alvarinho'],
    color: 'white',
    origin: 'spain',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [3, 3],
    },
    keyDescriptors: ['grapefruit', 'lemon', 'peach', 'saline'],
    story: [
      'Albariño er Galiciens stolthed og hoveddruen i Rías Baixas i det nordvestlige Spanien. Over grænsen i Portugal kaldes den Alvarinho og giver de bedste Vinho Verde-vine omkring Monção og Melgaço.',
      'En gammel legende fortæller, at druen blev bragt til Galicien af cisterciensermunke fra Rhinen. DNA-analyser peger dog på, at den er en ægte iberisk drue.',
      'I det fugtige atlanterhavsklima dyrkes den ofte på høje pergolaer, så luften kan cirkulere om klaserne. Den tykke skind og høje syre giver friske, aromatiske vine, der passer til egnens skaldyr.',
    ],
    verified: true,
    sources: [
      'Wine Folly, albarino grape profile, https://winefolly.com/grapes/albarino/ (hentet 2026-09-17)',
      'Wikipedia, Rías Baixas (DO), https://en.wikipedia.org/wiki/Rías_Baixas_(DO) (hentet 2026-09-17)',
    ],
  },
  {
    id: 'gruner-veltliner',
    name: 'Grüner Veltliner',
    aliases: [],
    color: 'white',
    origin: 'austria',
    typicalProfile: {
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 4],
      finish: [3, 4],
    },
    keyDescriptors: ['green-apple', 'grapefruit', 'white-pepper', 'wet-stone'],
    story: [
      'Grüner Veltliner er Østrigs mest plantede drue. Trods navnet har den ikke noget med Veltlin (Valtellina) at gøre. Den er en krydsning mellem Traminer og en næsten glemt drue, som blev genfundet i 2000 ved landsbyen St. Georgen i Burgenland.',
      'Druen er kendt for sin note af hvid peber og sin evne til at afspejle jordbunden. Wachau, Kamptal og Kremstal langs Donau er de klassiske områder, og i Wachau inddeles vinene efter modenhed i Steinfeder, Federspiel og Smaragd.',
      'En berømt blindsmagning i London i 2002, hvor topvine af Grüner Veltliner slog store Chardonnay-vine, gav druen international opmærksomhed.',
    ],
    verified: false,
    sources: [],
  },
  {
    id: 'semillon',
    name: 'Sémillon',
    aliases: [],
    color: 'white',
    origin: 'france',
    typicalProfile: {
      intensity: [2, 4],
      sweetness: [1, 5],
      acidity: [3, 4],
      tannin: null,
      alcohol: [2, 4],
      body: [3, 5],
      finish: [3, 5],
    },
    keyDescriptors: ['lemon', 'apricot', 'honey', 'wax', 'toast'],
    story: [
      "Sémillon stammer fra Bordeaux, hvor den er hoveddruen i Sauternes. Den tynde skind gør den modtagelig for ædelråd (botrytis), som koncentrerer sukker og syre og giver de berømte søde vine, med Château d'Yquem som det klassiske eksempel.",
      'I tørre Bordeaux-hvidvine blandes den med Sauvignon Blanc, hvor Sémillon bidrager med fylde og lagringsevne.',
      'Hunter Valley i Australien har sin helt egen tradition: Sémillon høstes tidligt, laves tør med lav alkohol og lagres i årevis på flaske, hvor den udvikler noter af ristet brød og honning.',
    ],
    note: 'Dry Bordeaux blends and botrytised Sauternes give very different profiles.',
    verified: false,
    sources: [],
  },
  {
    id: 'muscat',
    name: 'Muscat',
    aliases: ['Muscat Blanc à Petits Grains', 'Moscato', 'Moscatel'],
    color: 'white',
    origin: 'greece',
    typicalProfile: {
      intensity: [5, 5],
      sweetness: [1, 5],
      acidity: [2, 3],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 3],
      finish: [2, 3],
    },
    keyDescriptors: ['grape', 'orange-blossom', 'rose', 'honey'],
    story: [
      'Muscat er ikke én drue, men en hel familie af beslægtede druer, som regnes blandt de ældste, der dyrkes. De vigtigste er Muscat Blanc à Petits Grains, Muscat of Alexandria og Muscat Ottonel. Oprindelsen er usikker, men Grækenland og det østlige Middelhav nævnes ofte.',
      'Det særlige ved Muscat er, at vinen dufter af selve druen. Den er en af de få druer, hvor man tydeligt kan smage frugten i vinen.',
      "Druen laves i mange stilarter: let perlende og sød Moscato d'Asti i Piemonte, forstærkede vine som Muscat de Beaumes-de-Venise i Rhône, mørke, koncentrerede Rutherglen Muscat i Australien og tørre versioner i Alsace. Den bruges også som spisedrue.",
    ],
    note: 'Origin is uncertain; Greece/eastern Mediterranean is commonly cited. Needs review.',
    verified: false,
    sources: [],
  },
  {
    id: 'garganega',
    name: 'Garganega',
    aliases: [],
    color: 'white',
    origin: 'italy',
    typicalProfile: {
      intensity: [2, 3],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [2, 3],
    },
    keyDescriptors: ['pear', 'lemon', 'melon', 'nuts', 'chalk'],
    story: [
      'Garganega er Venetos vigtigste hvide drue og grundlaget for Soave, hvor den skal udgøre mindst 70 % af vinen. Den dyrkes også i nabobetegnelsen Gambellara.',
      'DNA-analyser har vist, at den er identisk med Grecanico, som dyrkes på Sicilien, og at den er beslægtet med en række andre italienske druer.',
      'På de vulkanske bakker i Soave Classico giver Garganega vine med mandel, hvide blomster og mineralitet. Af tørrede druer laves den søde Recioto di Soave.',
    ],
    verified: false,
    sources: [],
  },
]
