import type { Region } from '@/schema'

type RegionInput = Omit<Region, 'verified' | 'sources'> &
  Partial<Pick<Region, 'verified' | 'sources'>>

/** All starter content is unverified; this only saves repeating the two fields. */
const r = (input: RegionInput): Region => ({ verified: false, sources: [], ...input })

/**
 * Hierarchy: country > region > subregion > appellation via `parentId`.
 * `center` is [lng, lat]; coordinates are approximate town/area centres and must be reviewed.
 * `climate` is null for countries.
 */
export const regions: Region[] = [
  // ---------------------------------------------------------------- Countries
  r({
    id: 'france',
    name: 'Frankrig',
    type: 'country',
    parentId: null,
    world: 'old',
    climate: null,
    center: [2.5, 46.6],
    difficulty: 1,
  }),
  r({
    id: 'italy',
    name: 'Italien',
    type: 'country',
    parentId: null,
    world: 'old',
    climate: null,
    center: [12.5, 42.5],
    difficulty: 1,
  }),
  r({
    id: 'spain',
    name: 'Spanien',
    type: 'country',
    parentId: null,
    world: 'old',
    climate: null,
    center: [-3.7, 40.2],
    difficulty: 1,
  }),
  r({
    id: 'portugal',
    name: 'Portugal',
    type: 'country',
    parentId: null,
    world: 'old',
    climate: null,
    center: [-8.0, 39.6],
    difficulty: 1,
  }),
  r({
    id: 'germany',
    name: 'Tyskland',
    type: 'country',
    parentId: null,
    world: 'old',
    climate: null,
    center: [10.4, 51.1],
    difficulty: 1,
  }),
  r({
    id: 'austria',
    name: 'Østrig',
    type: 'country',
    parentId: null,
    world: 'old',
    climate: null,
    center: [14.5, 47.6],
    difficulty: 1,
  }),
  r({
    id: 'croatia',
    name: 'Kroatien',
    type: 'country',
    parentId: null,
    world: 'old',
    climate: null,
    center: [16.0, 45.3],
    difficulty: 3,
    note: 'Included only as the origin of Zinfandel/Primitivo.',
  }),
  r({
    id: 'greece',
    name: 'Grækenland',
    type: 'country',
    parentId: null,
    world: 'old',
    climate: null,
    center: [22.0, 39.0],
    difficulty: 3,
    note: 'Included only as the (uncertain) origin of Muscat.',
  }),
  r({
    id: 'usa',
    name: 'USA',
    type: 'country',
    parentId: null,
    world: 'new',
    climate: null,
    center: [-98.5, 39.8],
    difficulty: 1,
  }),
  r({
    id: 'australia',
    name: 'Australien',
    type: 'country',
    parentId: null,
    world: 'new',
    climate: null,
    center: [134.0, -25.5],
    difficulty: 1,
  }),
  r({
    id: 'new-zealand',
    name: 'New Zealand',
    type: 'country',
    parentId: null,
    world: 'new',
    climate: null,
    center: [172.5, -41.5],
    difficulty: 1,
  }),
  r({
    id: 'argentina',
    name: 'Argentina',
    type: 'country',
    parentId: null,
    world: 'new',
    climate: null,
    center: [-64.0, -34.0],
    difficulty: 1,
  }),
  r({
    id: 'chile',
    name: 'Chile',
    type: 'country',
    parentId: null,
    world: 'new',
    climate: null,
    center: [-71.0, -35.0],
    difficulty: 1,
  }),
  r({
    id: 'south-africa',
    name: 'Sydafrika',
    type: 'country',
    parentId: null,
    world: 'new',
    climate: null,
    center: [24.0, -29.0],
    difficulty: 1,
  }),

  // ---------------------------------------------------------------- France
  r({
    id: 'bordeaux',
    name: 'Bordeaux',
    type: 'region',
    parentId: 'france',
    world: 'old',
    climate: 'moderate',
    center: [-0.58, 44.84],
    difficulty: 1,
  }),
  r({
    id: 'pauillac',
    name: 'Pauillac',
    type: 'appellation',
    parentId: 'bordeaux',
    world: 'old',
    climate: 'moderate',
    center: [-0.75, 45.2],
    difficulty: 2,
  }),
  r({
    id: 'saint-emilion',
    name: 'Saint-Émilion',
    type: 'appellation',
    parentId: 'bordeaux',
    world: 'old',
    climate: 'moderate',
    center: [-0.16, 44.89],
    difficulty: 2,
  }),
  r({
    id: 'sauternes',
    name: 'Sauternes',
    type: 'appellation',
    parentId: 'bordeaux',
    world: 'old',
    climate: 'moderate',
    center: [-0.33, 44.53],
    difficulty: 2,
  }),
  r({
    id: 'bourgogne',
    name: 'Bourgogne',
    type: 'region',
    parentId: 'france',
    world: 'old',
    climate: 'cool',
    center: [4.85, 47.05],
    difficulty: 1,
  }),
  r({
    id: 'chablis',
    name: 'Chablis',
    type: 'appellation',
    parentId: 'bourgogne',
    world: 'old',
    climate: 'cool',
    center: [3.8, 47.81],
    difficulty: 2,
  }),
  r({
    id: 'cote-de-nuits',
    name: 'Côte de Nuits',
    type: 'subregion',
    parentId: 'bourgogne',
    world: 'old',
    climate: 'cool',
    center: [4.95, 47.18],
    difficulty: 2,
  }),
  r({
    id: 'cote-de-beaune',
    name: 'Côte de Beaune',
    type: 'subregion',
    parentId: 'bourgogne',
    world: 'old',
    climate: 'cool',
    center: [4.75, 46.98],
    difficulty: 2,
  }),
  r({
    id: 'beaujolais',
    name: 'Beaujolais',
    type: 'region',
    parentId: 'france',
    world: 'old',
    climate: 'moderate',
    center: [4.65, 46.15],
    difficulty: 2,
  }),
  r({
    id: 'northern-rhone',
    name: 'Nordlige Rhône',
    type: 'region',
    parentId: 'france',
    world: 'old',
    climate: 'moderate',
    center: [4.83, 45.05],
    difficulty: 2,
  }),
  r({
    id: 'southern-rhone',
    name: 'Sydlige Rhône',
    type: 'region',
    parentId: 'france',
    world: 'old',
    climate: 'warm',
    center: [4.85, 44.15],
    difficulty: 2,
  }),
  r({
    id: 'chateauneuf-du-pape',
    name: 'Châteauneuf-du-Pape',
    type: 'appellation',
    parentId: 'southern-rhone',
    world: 'old',
    climate: 'warm',
    center: [4.83, 44.06],
    difficulty: 2,
  }),
  r({
    id: 'loire',
    name: 'Loire',
    type: 'region',
    parentId: 'france',
    world: 'old',
    climate: 'cool',
    center: [0.5, 47.3],
    difficulty: 1,
  }),
  r({
    id: 'sancerre',
    name: 'Sancerre',
    type: 'appellation',
    parentId: 'loire',
    world: 'old',
    climate: 'cool',
    center: [2.83, 47.33],
    difficulty: 2,
  }),
  r({
    id: 'vouvray',
    name: 'Vouvray',
    type: 'appellation',
    parentId: 'loire',
    world: 'old',
    climate: 'cool',
    center: [0.8, 47.41],
    difficulty: 3,
  }),
  r({
    id: 'alsace',
    name: 'Alsace',
    type: 'region',
    parentId: 'france',
    world: 'old',
    climate: 'cool',
    center: [7.35, 48.3],
    difficulty: 2,
    note: 'Often described as cool-to-moderate continental; dry and sunny.',
  }),
  r({
    id: 'champagne',
    name: 'Champagne',
    type: 'region',
    parentId: 'france',
    world: 'old',
    climate: 'cool',
    center: [4.0, 49.05],
    difficulty: 1,
  }),

  // ---------------------------------------------------------------- Italy
  r({
    id: 'piemonte',
    name: 'Piemonte',
    type: 'region',
    parentId: 'italy',
    world: 'old',
    climate: 'moderate',
    center: [8.0, 44.7],
    difficulty: 1,
  }),
  r({
    id: 'barolo',
    name: 'Barolo',
    type: 'appellation',
    parentId: 'piemonte',
    world: 'old',
    climate: 'moderate',
    center: [7.94, 44.61],
    difficulty: 2,
  }),
  r({
    id: 'toscana',
    name: 'Toscana',
    type: 'region',
    parentId: 'italy',
    world: 'old',
    climate: 'warm',
    center: [11.2, 43.4],
    difficulty: 1,
  }),
  r({
    id: 'chianti-classico',
    name: 'Chianti Classico',
    type: 'appellation',
    parentId: 'toscana',
    world: 'old',
    climate: 'moderate',
    center: [11.3, 43.55],
    difficulty: 2,
    note: 'Hilly and cooler than the Tuscan coast; some sources say warm.',
  }),
  r({
    id: 'brunello-di-montalcino',
    name: 'Brunello di Montalcino',
    type: 'appellation',
    parentId: 'toscana',
    world: 'old',
    climate: 'warm',
    center: [11.49, 43.06],
    difficulty: 2,
  }),
  r({
    id: 'veneto',
    name: 'Veneto',
    type: 'region',
    parentId: 'italy',
    world: 'old',
    climate: 'moderate',
    center: [11.5, 45.5],
    difficulty: 1,
  }),
  r({
    id: 'soave',
    name: 'Soave',
    type: 'appellation',
    parentId: 'veneto',
    world: 'old',
    climate: 'moderate',
    center: [11.25, 45.42],
    difficulty: 3,
  }),
  r({
    id: 'puglia',
    name: 'Puglia',
    type: 'region',
    parentId: 'italy',
    world: 'old',
    climate: 'warm',
    center: [16.5, 41.0],
    difficulty: 2,
  }),

  // ---------------------------------------------------------------- Spain & Portugal
  r({
    id: 'rioja',
    name: 'Rioja',
    type: 'region',
    parentId: 'spain',
    world: 'old',
    climate: 'moderate',
    center: [-2.45, 42.45],
    difficulty: 1,
  }),
  r({
    id: 'ribera-del-duero',
    name: 'Ribera del Duero',
    type: 'region',
    parentId: 'spain',
    world: 'old',
    climate: 'moderate',
    center: [-3.7, 41.65],
    difficulty: 2,
    note: 'Continental at ~800 m: hot days, cold nights. Some sources classify as warm.',
  }),
  r({
    id: 'rias-baixas',
    name: 'Rías Baixas',
    type: 'region',
    parentId: 'spain',
    world: 'old',
    climate: 'cool',
    center: [-8.7, 42.5],
    difficulty: 2,
    note: 'WSET describes it as moderate maritime; wines show cool-climate acidity. Review.',
  }),
  r({
    id: 'priorat',
    name: 'Priorat',
    type: 'region',
    parentId: 'spain',
    world: 'old',
    climate: 'warm',
    center: [0.82, 41.2],
    difficulty: 3,
  }),
  r({
    id: 'douro',
    name: 'Douro',
    type: 'region',
    parentId: 'portugal',
    world: 'old',
    climate: 'warm',
    center: [-7.6, 41.17],
    difficulty: 1,
  }),

  // ---------------------------------------------------------------- Germany & Austria
  r({
    id: 'mosel',
    name: 'Mosel',
    type: 'region',
    parentId: 'germany',
    world: 'old',
    climate: 'cool',
    center: [7.0, 49.9],
    difficulty: 1,
  }),
  r({
    id: 'rheingau',
    name: 'Rheingau',
    type: 'region',
    parentId: 'germany',
    world: 'old',
    climate: 'cool',
    center: [8.0, 50.02],
    difficulty: 2,
  }),
  r({
    id: 'wachau',
    name: 'Wachau',
    type: 'region',
    parentId: 'austria',
    world: 'old',
    climate: 'cool',
    center: [15.45, 48.38],
    difficulty: 2,
    note: 'Cool-to-moderate continental.',
  }),

  // ---------------------------------------------------------------- USA
  r({
    id: 'napa-valley',
    name: 'Napa Valley',
    type: 'region',
    parentId: 'usa',
    world: 'new',
    climate: 'warm',
    center: [-122.3, 38.45],
    difficulty: 1,
  }),
  r({
    id: 'sonoma',
    name: 'Sonoma',
    type: 'region',
    parentId: 'usa',
    world: 'new',
    climate: 'moderate',
    center: [-122.8, 38.45],
    difficulty: 2,
    note: 'Very varied; coastal parts are cool, inland parts warm.',
  }),
  r({
    id: 'willamette-valley',
    name: 'Willamette Valley',
    type: 'region',
    parentId: 'usa',
    world: 'new',
    climate: 'cool',
    center: [-123.0, 45.2],
    difficulty: 2,
  }),

  // ---------------------------------------------------------------- Australia & New Zealand
  r({
    id: 'barossa-valley',
    name: 'Barossa Valley',
    type: 'region',
    parentId: 'australia',
    world: 'new',
    climate: 'warm',
    center: [138.95, -34.55],
    difficulty: 1,
  }),
  r({
    id: 'clare-valley',
    name: 'Clare Valley',
    type: 'region',
    parentId: 'australia',
    world: 'new',
    climate: 'moderate',
    center: [138.6, -33.85],
    difficulty: 3,
    note: 'Warm days but altitude and cool nights; Riesling keeps high acidity. Review.',
  }),
  r({
    id: 'margaret-river',
    name: 'Margaret River',
    type: 'region',
    parentId: 'australia',
    world: 'new',
    climate: 'moderate',
    center: [115.07, -33.85],
    difficulty: 2,
  }),
  r({
    id: 'yarra-valley',
    name: 'Yarra Valley',
    type: 'region',
    parentId: 'australia',
    world: 'new',
    climate: 'cool',
    center: [145.5, -37.7],
    difficulty: 2,
  }),
  r({
    id: 'marlborough',
    name: 'Marlborough',
    type: 'region',
    parentId: 'new-zealand',
    world: 'new',
    climate: 'cool',
    center: [173.75, -41.5],
    difficulty: 1,
  }),
  r({
    id: 'central-otago',
    name: 'Central Otago',
    type: 'region',
    parentId: 'new-zealand',
    world: 'new',
    climate: 'cool',
    center: [169.2, -45.0],
    difficulty: 2,
  }),

  // ---------------------------------------------------------------- South America & South Africa
  r({
    id: 'mendoza',
    name: 'Mendoza',
    type: 'region',
    parentId: 'argentina',
    world: 'new',
    climate: 'warm',
    center: [-68.85, -33.0],
    difficulty: 1,
    note: 'High altitude moderates the heat; often described as warm continental.',
  }),
  r({
    id: 'maipo-valley',
    name: 'Valle del Maipo',
    type: 'region',
    parentId: 'chile',
    world: 'new',
    climate: 'warm',
    center: [-70.7, -33.7],
    difficulty: 2,
  }),
  r({
    id: 'stellenbosch',
    name: 'Stellenbosch',
    type: 'region',
    parentId: 'south-africa',
    world: 'new',
    climate: 'warm',
    center: [18.86, -33.93],
    difficulty: 1,
    note: 'Warm Mediterranean with cooling ocean breezes.',
  }),
]
