import type { Style } from '@/schema'

type StyleInput = Omit<Style, 'verified' | 'sources'> & Partial<Pick<Style, 'verified' | 'sources'>>

/** All starter content is unverified; this only saves repeating the two fields. */
const s = (input: StyleInput): Style => ({ verified: false, sources: [], ...input })

/**
 * Classic grape × region styles. Profile ranges use the 1–5 scale
 * (1=low, 2=medium-, 3=medium, 4=medium+, 5=high). Tannin is null for whites.
 * Where the style is an appellation not in regions.ts, the nearest listed region is used and noted.
 */
export const styles: Style[] = [
  // ================================================================ WHITE
  s({
    id: 'sancerre',
    name: 'Sancerre',
    color: 'white',
    grapeIds: ['sauvignon-blanc'],
    regionId: 'sancerre',
    profile: {
      appearance: 'lemon-green',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    descriptorIds: ['gooseberry', 'grapefruit', 'grass', 'flint', 'elderflower'],
    oak: 'none',
    difficulty: 1,
  }),
  s({
    id: 'marlborough-sauvignon-blanc',
    name: 'Marlborough Sauvignon Blanc',
    color: 'white',
    grapeIds: ['sauvignon-blanc'],
    regionId: 'marlborough',
    profile: {
      appearance: 'lemon-green',
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    descriptorIds: ['passion-fruit', 'gooseberry', 'grapefruit', 'grass', 'tomato-leaf'],
    oak: 'none',
    difficulty: 1,
  }),
  s({
    id: 'bordeaux-blanc',
    name: 'Bordeaux Blanc',
    color: 'white',
    grapeIds: ['sauvignon-blanc', 'semillon'],
    regionId: 'bordeaux',
    profile: {
      appearance: 'lemon',
      intensity: [3, 3],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: null,
      alcohol: [3, 3],
      body: [3, 3],
      finish: [3, 3],
    },
    descriptorIds: ['lemon', 'grapefruit', 'wax', 'toast', 'grass'],
    oak: 'light',
    difficulty: 3,
    note: 'Represents dry white Bordeaux (e.g. Pessac-Léognan), often barrel-fermented.',
  }),
  s({
    id: 'chablis',
    name: 'Chablis',
    color: 'white',
    grapeIds: ['chardonnay'],
    regionId: 'chablis',
    profile: {
      appearance: 'lemon',
      intensity: [2, 3],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    descriptorIds: ['green-apple', 'lemon', 'wet-stone', 'flint', 'chalk'],
    oak: 'none',
    difficulty: 2,
  }),
  s({
    id: 'cote-de-beaune-blanc',
    name: 'Bourgogne Blanc (Côte de Beaune)',
    color: 'white',
    grapeIds: ['chardonnay'],
    regionId: 'cote-de-beaune',
    profile: {
      appearance: 'lemon',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: null,
      alcohol: [3, 4],
      body: [3, 4],
      finish: [4, 5],
    },
    descriptorIds: ['lemon', 'peach', 'nuts', 'butter', 'toast', 'flint'],
    oak: 'light',
    difficulty: 2,
    note: 'Represents Meursault / Puligny-Montrachet / Chassagne-Montrachet.',
  }),
  s({
    id: 'napa-chardonnay',
    name: 'Napa Valley Chardonnay',
    color: 'white',
    grapeIds: ['chardonnay'],
    regionId: 'napa-valley',
    profile: {
      appearance: 'gold',
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: null,
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    descriptorIds: ['pineapple', 'peach', 'vanilla', 'butter', 'toast'],
    oak: 'pronounced',
    difficulty: 1,
  }),
  s({
    id: 'margaret-river-chardonnay',
    name: 'Margaret River Chardonnay',
    color: 'white',
    grapeIds: ['chardonnay'],
    regionId: 'margaret-river',
    profile: {
      appearance: 'lemon',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: null,
      alcohol: [3, 4],
      body: [3, 4],
      finish: [4, 4],
    },
    descriptorIds: ['grapefruit', 'nectarine', 'peach', 'toast', 'flint'],
    oak: 'light',
    difficulty: 3,
  }),
  s({
    id: 'mosel-riesling-kabinett',
    name: 'Mosel Riesling Kabinett',
    color: 'white',
    grapeIds: ['riesling'],
    regionId: 'mosel',
    profile: {
      appearance: 'lemon-green',
      intensity: [3, 4],
      sweetness: [2, 3],
      acidity: [5, 5],
      tannin: null,
      alcohol: [1, 2],
      body: [1, 2],
      finish: [3, 4],
    },
    descriptorIds: ['green-apple', 'lime', 'peach', 'wet-stone', 'honeysuckle'],
    oak: 'none',
    difficulty: 2,
  }),
  s({
    id: 'rheingau-riesling-trocken',
    name: 'Rheingau Riesling Trocken',
    color: 'white',
    grapeIds: ['riesling'],
    regionId: 'rheingau',
    profile: {
      appearance: 'lemon',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    descriptorIds: ['green-apple', 'lemon', 'peach', 'wet-stone', 'petrol'],
    oak: 'none',
    difficulty: 3,
  }),
  s({
    id: 'alsace-riesling',
    name: 'Alsace Riesling',
    color: 'white',
    grapeIds: ['riesling'],
    regionId: 'alsace',
    profile: {
      appearance: 'lemon',
      intensity: [3, 4],
      sweetness: [1, 2],
      acidity: [4, 5],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    descriptorIds: ['lemon', 'green-apple', 'peach', 'wet-stone', 'petrol'],
    oak: 'none',
    difficulty: 3,
  }),
  s({
    id: 'clare-valley-riesling',
    name: 'Clare Valley Riesling',
    color: 'white',
    grapeIds: ['riesling'],
    regionId: 'clare-valley',
    profile: {
      appearance: 'lemon-green',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 2],
      finish: [3, 4],
    },
    descriptorIds: ['lime', 'lemon', 'green-apple', 'honeysuckle', 'petrol'],
    oak: 'none',
    difficulty: 2,
  }),
  s({
    id: 'alsace-gewurztraminer',
    name: 'Alsace Gewürztraminer',
    color: 'white',
    grapeIds: ['gewurztraminer'],
    regionId: 'alsace',
    profile: {
      appearance: 'gold',
      intensity: [5, 5],
      sweetness: [1, 3],
      acidity: [2, 2],
      tannin: null,
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    descriptorIds: ['lychee', 'rose', 'ginger', 'honey', 'orange-peel'],
    oak: 'none',
    difficulty: 1,
  }),
  s({
    id: 'alsace-pinot-gris',
    name: 'Alsace Pinot Gris',
    color: 'white',
    grapeIds: ['pinot-grigio'],
    regionId: 'alsace',
    profile: {
      appearance: 'gold',
      intensity: [3, 4],
      sweetness: [1, 3],
      acidity: [2, 3],
      tannin: null,
      alcohol: [4, 4],
      body: [4, 4],
      finish: [3, 4],
    },
    descriptorIds: ['pear', 'apricot', 'honey', 'ginger', 'smoke'],
    oak: 'none',
    difficulty: 3,
  }),
  s({
    id: 'muscat-d-alsace',
    name: "Muscat d'Alsace",
    color: 'white',
    grapeIds: ['muscat'],
    regionId: 'alsace',
    profile: {
      appearance: 'lemon-green',
      intensity: [5, 5],
      sweetness: [1, 1],
      acidity: [2, 3],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [2, 3],
    },
    descriptorIds: ['grape', 'orange-blossom', 'rose', 'elderflower'],
    oak: 'none',
    difficulty: 2,
  }),
  s({
    id: 'pinot-grigio-veneto',
    name: 'Pinot Grigio (Veneto)',
    color: 'white',
    grapeIds: ['pinot-grigio'],
    regionId: 'veneto',
    profile: {
      appearance: 'lemon-green',
      intensity: [2, 2],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 2],
      finish: [2, 2],
    },
    descriptorIds: ['pear', 'lemon', 'green-apple', 'acacia'],
    oak: 'none',
    difficulty: 1,
    note: 'Represents the light delle Venezie style.',
  }),
  s({
    id: 'soave-classico',
    name: 'Soave Classico',
    color: 'white',
    grapeIds: ['garganega'],
    regionId: 'soave',
    profile: {
      appearance: 'lemon',
      intensity: [2, 3],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [2, 3],
    },
    descriptorIds: ['pear', 'lemon', 'melon', 'nuts', 'chalk'],
    oak: 'none',
    difficulty: 3,
  }),
  s({
    id: 'vouvray-sec',
    name: 'Vouvray Sec',
    color: 'white',
    grapeIds: ['chenin-blanc'],
    regionId: 'vouvray',
    profile: {
      appearance: 'lemon',
      intensity: [3, 4],
      sweetness: [1, 2],
      acidity: [5, 5],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    descriptorIds: ['green-apple', 'quince', 'honey', 'wax', 'chalk'],
    oak: 'none',
    difficulty: 3,
  }),
  s({
    id: 'stellenbosch-chenin-blanc',
    name: 'Stellenbosch Chenin Blanc',
    color: 'white',
    grapeIds: ['chenin-blanc'],
    regionId: 'stellenbosch',
    profile: {
      appearance: 'lemon',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: null,
      alcohol: [3, 4],
      body: [3, 3],
      finish: [3, 3],
    },
    descriptorIds: ['green-apple', 'pineapple', 'peach', 'honey'],
    oak: 'none',
    difficulty: 3,
  }),
  s({
    id: 'condrieu',
    name: 'Condrieu',
    color: 'white',
    grapeIds: ['viognier'],
    regionId: 'northern-rhone',
    profile: {
      appearance: 'gold',
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [2, 3],
      tannin: null,
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    descriptorIds: ['apricot', 'peach', 'honeysuckle', 'orange-blossom'],
    oak: 'light',
    difficulty: 2,
    note: 'Condrieu is an appellation within the Northern Rhône; not listed separately in regions.ts.',
  }),
  s({
    id: 'rias-baixas-albarino',
    name: 'Rías Baixas Albariño',
    color: 'white',
    grapeIds: ['albarino'],
    regionId: 'rias-baixas',
    profile: {
      appearance: 'lemon-green',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: null,
      alcohol: [2, 3],
      body: [2, 3],
      finish: [3, 3],
    },
    descriptorIds: ['grapefruit', 'lemon', 'peach', 'saline'],
    oak: 'none',
    difficulty: 2,
  }),
  s({
    id: 'wachau-gruner-veltliner',
    name: 'Wachau Grüner Veltliner',
    color: 'white',
    grapeIds: ['gruner-veltliner'],
    regionId: 'wachau',
    profile: {
      appearance: 'lemon-green',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: null,
      alcohol: [3, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    descriptorIds: ['green-apple', 'grapefruit', 'white-pepper', 'wet-stone'],
    oak: 'none',
    difficulty: 2,
  }),

  // ================================================================ SWEET
  s({
    id: 'sauternes',
    name: 'Sauternes',
    color: 'sweet',
    grapeIds: ['semillon', 'sauvignon-blanc'],
    regionId: 'sauternes',
    profile: {
      appearance: 'gold',
      intensity: [5, 5],
      sweetness: [5, 5],
      acidity: [4, 4],
      tannin: null,
      alcohol: [3, 4],
      body: [4, 5],
      finish: [5, 5],
    },
    descriptorIds: ['apricot', 'honey', 'orange-peel', 'dried-fruit', 'vanilla'],
    oak: 'light',
    difficulty: 2,
    note: 'Botrytised sweet wine. Included so Sémillon has a classic style; sweet wines are otherwise phase 10.',
  }),

  // ================================================================ RED
  s({
    id: 'pauillac',
    name: 'Pauillac',
    color: 'red',
    grapeIds: ['cabernet-sauvignon', 'merlot'],
    regionId: 'pauillac',
    profile: {
      appearance: 'ruby',
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [4, 5],
      alcohol: [3, 4],
      body: [4, 5],
      finish: [4, 5],
    },
    descriptorIds: ['blackcurrant', 'cedar', 'tobacco', 'green-bell-pepper', 'toast'],
    oak: 'pronounced',
    difficulty: 2,
  }),
  s({
    id: 'napa-cabernet-sauvignon',
    name: 'Napa Valley Cabernet Sauvignon',
    color: 'red',
    grapeIds: ['cabernet-sauvignon'],
    regionId: 'napa-valley',
    profile: {
      appearance: 'ruby',
      intensity: [5, 5],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: [4, 5],
      alcohol: [4, 5],
      body: [5, 5],
      finish: [4, 5],
    },
    descriptorIds: ['blackcurrant', 'black-cherry', 'vanilla', 'chocolate', 'mint'],
    oak: 'pronounced',
    difficulty: 1,
  }),
  s({
    id: 'margaret-river-cabernet-sauvignon',
    name: 'Margaret River Cabernet Sauvignon',
    color: 'red',
    grapeIds: ['cabernet-sauvignon', 'merlot'],
    regionId: 'margaret-river',
    profile: {
      appearance: 'ruby',
      intensity: [4, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [4, 4],
      alcohol: [3, 4],
      body: [4, 4],
      finish: [4, 4],
    },
    descriptorIds: ['blackcurrant', 'cedar', 'mint', 'tobacco', 'black-plum'],
    oak: 'light',
    difficulty: 3,
  }),
  s({
    id: 'maipo-cabernet-sauvignon',
    name: 'Maipo Cabernet Sauvignon',
    color: 'red',
    grapeIds: ['cabernet-sauvignon'],
    regionId: 'maipo-valley',
    profile: {
      appearance: 'ruby',
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [4, 4],
      alcohol: [4, 4],
      body: [4, 4],
      finish: [3, 4],
    },
    descriptorIds: ['blackcurrant', 'mint', 'eucalyptus', 'black-plum', 'vanilla'],
    oak: 'light',
    difficulty: 3,
  }),
  s({
    id: 'stellenbosch-cabernet-sauvignon',
    name: 'Stellenbosch Cabernet Sauvignon',
    color: 'red',
    grapeIds: ['cabernet-sauvignon'],
    regionId: 'stellenbosch',
    profile: {
      appearance: 'ruby',
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [4, 4],
      alcohol: [4, 4],
      body: [4, 4],
      finish: [4, 4],
    },
    descriptorIds: ['blackcurrant', 'black-plum', 'cedar', 'smoke', 'dried-herbs'],
    oak: 'pronounced',
    difficulty: 3,
  }),
  s({
    id: 'saint-emilion',
    name: 'Saint-Émilion',
    color: 'red',
    grapeIds: ['merlot', 'cabernet-franc'],
    regionId: 'saint-emilion',
    profile: {
      appearance: 'ruby',
      intensity: [4, 4],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [3, 4],
      alcohol: [3, 4],
      body: [4, 4],
      finish: [4, 4],
    },
    descriptorIds: ['red-plum', 'black-plum', 'cedar', 'tobacco', 'chocolate'],
    oak: 'pronounced',
    difficulty: 3,
  }),
  s({
    id: 'napa-merlot',
    name: 'Napa Valley Merlot',
    color: 'red',
    grapeIds: ['merlot'],
    regionId: 'napa-valley',
    profile: {
      appearance: 'ruby',
      intensity: [4, 4],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    descriptorIds: ['black-plum', 'black-cherry', 'chocolate', 'vanilla', 'coffee'],
    oak: 'pronounced',
    difficulty: 3,
  }),
  s({
    id: 'cote-de-nuits-rouge',
    name: 'Bourgogne Rouge (Côte de Nuits)',
    color: 'red',
    grapeIds: ['pinot-noir'],
    regionId: 'cote-de-nuits',
    profile: {
      appearance: 'ruby',
      intensity: [3, 3],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [2, 3],
      alcohol: [3, 3],
      body: [2, 3],
      finish: [3, 4],
    },
    descriptorIds: ['red-cherry', 'raspberry', 'forest-floor', 'violet', 'mushroom'],
    oak: 'light',
    difficulty: 2,
    note: 'Represents Gevrey-Chambertin / Nuits-Saint-Georges / Vosne-Romanée village and premier cru wines.',
  }),
  s({
    id: 'willamette-pinot-noir',
    name: 'Willamette Valley Pinot Noir',
    color: 'red',
    grapeIds: ['pinot-noir'],
    regionId: 'willamette-valley',
    profile: {
      appearance: 'ruby',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [2, 3],
      alcohol: [3, 4],
      body: [3, 3],
      finish: [3, 4],
    },
    descriptorIds: ['red-cherry', 'cranberry', 'raspberry', 'forest-floor', 'vanilla'],
    oak: 'light',
    difficulty: 3,
  }),
  s({
    id: 'central-otago-pinot-noir',
    name: 'Central Otago Pinot Noir',
    color: 'red',
    grapeIds: ['pinot-noir'],
    regionId: 'central-otago',
    profile: {
      appearance: 'ruby',
      intensity: [4, 4],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [3, 3],
      alcohol: [3, 4],
      body: [3, 4],
      finish: [3, 4],
    },
    descriptorIds: ['black-cherry', 'raspberry', 'thyme', 'vanilla', 'red-plum'],
    oak: 'light',
    difficulty: 2,
  }),
  s({
    id: 'yarra-valley-pinot-noir',
    name: 'Yarra Valley Pinot Noir',
    color: 'red',
    grapeIds: ['pinot-noir'],
    regionId: 'yarra-valley',
    profile: {
      appearance: 'ruby',
      intensity: [3, 3],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [2, 3],
      alcohol: [3, 3],
      body: [3, 3],
      finish: [3, 3],
    },
    descriptorIds: ['red-cherry', 'strawberry', 'dried-herbs', 'vanilla'],
    oak: 'light',
    difficulty: 3,
  }),
  s({
    id: 'cote-rotie',
    name: 'Côte-Rôtie',
    color: 'red',
    grapeIds: ['syrah'],
    regionId: 'northern-rhone',
    profile: {
      appearance: 'ruby',
      intensity: [4, 5],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [4, 4],
      alcohol: [3, 4],
      body: [4, 4],
      finish: [4, 5],
    },
    descriptorIds: ['blackberry', 'black-pepper', 'violet', 'smoke', 'liquorice'],
    oak: 'light',
    difficulty: 2,
    note: 'Represents Northern Rhône Syrah in general (Hermitage, Saint-Joseph, Crozes-Hermitage).',
  }),
  s({
    id: 'barossa-shiraz',
    name: 'Barossa Shiraz',
    color: 'red',
    grapeIds: ['syrah'],
    regionId: 'barossa-valley',
    profile: {
      appearance: 'purple',
      intensity: [5, 5],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: [4, 4],
      alcohol: [5, 5],
      body: [5, 5],
      finish: [4, 4],
    },
    descriptorIds: ['blackberry', 'black-plum', 'chocolate', 'vanilla', 'liquorice', 'eucalyptus'],
    oak: 'pronounced',
    difficulty: 1,
  }),
  s({
    id: 'chateauneuf-du-pape',
    name: 'Châteauneuf-du-Pape',
    color: 'red',
    grapeIds: ['grenache', 'syrah'],
    regionId: 'chateauneuf-du-pape',
    profile: {
      appearance: 'ruby',
      intensity: [4, 4],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [5, 5],
      body: [4, 5],
      finish: [4, 4],
    },
    descriptorIds: [
      'strawberry',
      'raspberry',
      'dried-herbs',
      'black-pepper',
      'liquorice',
      'leather',
    ],
    oak: 'light',
    difficulty: 2,
    note: 'Mourvèdre is also a principal grape but is not in the starter grape list.',
  }),
  s({
    id: 'priorat',
    name: 'Priorat',
    color: 'red',
    grapeIds: ['grenache'],
    regionId: 'priorat',
    profile: {
      appearance: 'ruby',
      intensity: [5, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [4, 5],
      alcohol: [5, 5],
      body: [5, 5],
      finish: [4, 5],
    },
    descriptorIds: ['black-cherry', 'blackberry', 'liquorice', 'wet-stone', 'toast'],
    oak: 'pronounced',
    difficulty: 3,
    note: 'Cariñena (Carignan) is the other principal grape but is not in the starter grape list.',
  }),
  s({
    id: 'rioja-reserva',
    name: 'Rioja Reserva',
    color: 'red',
    grapeIds: ['tempranillo', 'grenache'],
    regionId: 'rioja',
    profile: {
      appearance: 'garnet',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [3, 4],
      alcohol: [3, 4],
      body: [3, 4],
      finish: [4, 4],
    },
    descriptorIds: ['red-cherry', 'vanilla', 'coconut', 'leather', 'tobacco', 'dried-fruit'],
    oak: 'pronounced',
    difficulty: 1,
  }),
  s({
    id: 'ribera-del-duero',
    name: 'Ribera del Duero',
    color: 'red',
    grapeIds: ['tempranillo'],
    regionId: 'ribera-del-duero',
    profile: {
      appearance: 'ruby',
      intensity: [5, 5],
      sweetness: [1, 1],
      acidity: [3, 4],
      tannin: [4, 5],
      alcohol: [4, 5],
      body: [5, 5],
      finish: [4, 4],
    },
    descriptorIds: ['black-plum', 'blackberry', 'vanilla', 'toast', 'liquorice'],
    oak: 'pronounced',
    difficulty: 2,
  }),
  s({
    id: 'chianti-classico',
    name: 'Chianti Classico',
    color: 'red',
    grapeIds: ['sangiovese'],
    regionId: 'chianti-classico',
    profile: {
      appearance: 'ruby',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: [4, 4],
      alcohol: [3, 4],
      body: [3, 4],
      finish: [3, 4],
    },
    descriptorIds: ['red-cherry', 'red-plum', 'dried-herbs', 'tomato-leaf', 'leather'],
    oak: 'light',
    difficulty: 1,
  }),
  s({
    id: 'brunello-di-montalcino',
    name: 'Brunello di Montalcino',
    color: 'red',
    grapeIds: ['sangiovese'],
    regionId: 'brunello-di-montalcino',
    profile: {
      appearance: 'garnet',
      intensity: [4, 4],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: [4, 5],
      alcohol: [4, 4],
      body: [4, 5],
      finish: [5, 5],
    },
    descriptorIds: ['red-cherry', 'black-cherry', 'leather', 'tobacco', 'dried-herbs'],
    oak: 'light',
    difficulty: 3,
  }),
  s({
    id: 'barolo',
    name: 'Barolo',
    color: 'red',
    grapeIds: ['nebbiolo'],
    regionId: 'barolo',
    profile: {
      appearance: 'garnet',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: [5, 5],
      alcohol: [4, 4],
      body: [3, 4],
      finish: [5, 5],
    },
    descriptorIds: ['rose', 'tar', 'red-cherry', 'liquorice', 'dried-herbs'],
    oak: 'light',
    difficulty: 2,
  }),
  s({
    id: 'barbera-d-asti',
    name: "Barbera d'Asti",
    color: 'red',
    grapeIds: ['barbera'],
    regionId: 'piemonte',
    profile: {
      appearance: 'ruby',
      intensity: [3, 4],
      sweetness: [1, 1],
      acidity: [5, 5],
      tannin: [2, 3],
      alcohol: [3, 4],
      body: [3, 3],
      finish: [3, 3],
    },
    descriptorIds: ['red-cherry', 'red-plum', 'blackberry', 'black-pepper'],
    oak: 'none',
    difficulty: 3,
    note: 'Asti is not a separate entry in regions.ts; mapped to Piemonte.',
  }),
  s({
    id: 'mendoza-malbec',
    name: 'Mendoza Malbec',
    color: 'red',
    grapeIds: ['malbec'],
    regionId: 'mendoza',
    profile: {
      appearance: 'purple',
      intensity: [5, 5],
      sweetness: [1, 1],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [4, 5],
      body: [4, 5],
      finish: [3, 4],
    },
    descriptorIds: ['blackberry', 'black-plum', 'violet', 'vanilla', 'chocolate'],
    oak: 'pronounced',
    difficulty: 1,
  }),
  s({
    id: 'sonoma-zinfandel',
    name: 'Sonoma Zinfandel',
    color: 'red',
    grapeIds: ['zinfandel'],
    regionId: 'sonoma',
    profile: {
      appearance: 'ruby',
      intensity: [5, 5],
      sweetness: [1, 2],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [5, 5],
      body: [5, 5],
      finish: [4, 4],
    },
    descriptorIds: ['blackberry', 'raspberry', 'black-pepper', 'dried-fruit', 'vanilla'],
    oak: 'light',
    difficulty: 2,
    note: 'Represents Dry Creek Valley Zinfandel.',
  }),
  s({
    id: 'primitivo-di-manduria',
    name: 'Primitivo di Manduria',
    color: 'red',
    grapeIds: ['zinfandel'],
    regionId: 'puglia',
    profile: {
      appearance: 'ruby',
      intensity: [5, 5],
      sweetness: [1, 2],
      acidity: [3, 3],
      tannin: [3, 4],
      alcohol: [5, 5],
      body: [5, 5],
      finish: [3, 4],
    },
    descriptorIds: ['black-plum', 'dried-fruit', 'blackberry', 'liquorice', 'chocolate'],
    oak: 'light',
    difficulty: 3,
    note: 'Same grape as Zinfandel; deliberately close to Sonoma Zinfandel and hard to separate.',
  }),
  s({
    id: 'beaujolais',
    name: 'Beaujolais',
    color: 'red',
    grapeIds: ['gamay'],
    regionId: 'beaujolais',
    profile: {
      appearance: 'purple',
      intensity: [3, 3],
      sweetness: [1, 1],
      acidity: [4, 4],
      tannin: [2, 2],
      alcohol: [2, 3],
      body: [2, 2],
      finish: [2, 3],
    },
    descriptorIds: ['raspberry', 'red-cherry', 'banana', 'violet', 'cranberry'],
    oak: 'none',
    difficulty: 1,
    note: 'Represents Beaujolais / Beaujolais-Villages made with carbonic maceration.',
  }),
  s({
    id: 'chinon',
    name: 'Chinon',
    color: 'red',
    grapeIds: ['cabernet-franc'],
    regionId: 'loire',
    profile: {
      appearance: 'ruby',
      intensity: [3, 3],
      sweetness: [1, 1],
      acidity: [4, 5],
      tannin: [3, 3],
      alcohol: [2, 3],
      body: [2, 3],
      finish: [3, 3],
    },
    descriptorIds: ['raspberry', 'redcurrant', 'green-bell-pepper', 'violet', 'wet-stone'],
    oak: 'none',
    difficulty: 3,
    note: 'Chinon is not a separate entry in regions.ts; mapped to Loire.',
  }),
]
